[[UNRESOLVED_REF]]
id = "ARCHIVEXL_12100"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.21.0 or higher"

[[UNRESOLVED_METHOD]]
id = "ARCHIVEXL_12100"
span_starts_with = "ArchiveXL"
message = "Install ArchiveXL 1.21.0 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_11007"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.10.7 or higher"

[[UNRESOLVED_FN]]
id = "CODEWARE_11500"
span_starts_with = "Print(command)"
message = "Install Codeware 1.15.0 or higher"

[[UNRESOLVED_FN]]
id = "CODEWARE_11500"
line_contains = "UTF8StrLower"
message = "Install Codeware 1.15.0 or higher"

[[UNRESOLVED_METHOD]]
id = "CODEWARE_11500"
line_contains = "ForgetItemID"
message = "Install Codeware 1.15.0 or higher"

[[UNRESOLVED_TYPE]]
id = "CODEWARE_11500"
line_contains = "InMenuPopup"
message = "Install Codeware 1.15.0 or higher"

[[UNRESOLVED_METHOD]]
id = "EQEX_MIX"
line_contains = "method CheckRequirements not found on EquipmentEx"
message = "Remove r6/scripts/EquipmentEx and clean install the latest version of Equipment-EX"
